version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/pgsql/data/
    volumes:
      - main_storage:/var/lib/pgsql/data/
    ports:
      - "127.0.0.1:5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  main_storage:
